### ISSUE TITLE
Case Folding (Section 2.1) - Sharp S example

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#68] opened 2016-02-04 03:21 UTC
I recommend not using Sharp S as an example.   While the explanation is consistent with the Unicode one, with the introduction of U+1E9E, one of the main arguments for that particular "case" folding/ mapping has dissolved into "stability", i.e., "we did it that way before so we need to continue" (not necessarily a bad argument, but different from "need to map to "SS" because there is no upper case and then back to "ss").   There is also a case to be made that the appropriateness or inappropriateness of that mapping is narrowly locale-dependent and is seems to me that this section doesn't want to go there.

**Comment by klensin** [comment] 2016-02-04 03:37
Note that "locale-dependent" as used above, is different from "language sensitive" (or "language dependent") as used further on in the text... at least unless one defines languages very precisely by place and/or time.   The Turkic example, which is cited so often that many people believe it is the only case (and is cited in TUS as "locale-dependent" when it is really language-dependent), is ultimately not a lot different from the cases in which, while "ß" can always be transformed into "ss" (even if the result is seen as a serious spelling error on some locales), "ss" cannot be transformed in some cases to "ß" without loss of meaning and/or silly states.  

The Unicode Standard seems to say that the main application of case folding is for caseless matching (subsection of that name in TUS 7.0, Section 5.18) and that using case folding for mapping and replacement operations is unwise.  It seems to me that point is important; it is hard to find or deduce from this section.

**Comment by duerst** [comment] 2016-02-04 09:23
Re. sharp s (ß) and U+1E9E: The upper-case mapping from ß to SS is not (only) for stability, it is still the rule wherever the ß is actually used. There have been times where U+1E9E was somewhat popular, to the extent that even the Duden (German reference orthography) used it on all caps titles.
The availability of the character in Unicode, trickling down to fonts, may eventually be picked up more or less in practice (there is already such a practice currently, but it's very small). Then later it may possibly make it into orthography as a sanctioned variant or even as the 'right thing to do'. But we are a long time away from that state.
So the claim "Need to map to 'SS' because there's no upper case for ß" is wrong, but the claim "the correct upper case of ß is 'SS' is nevertheless firmly valid".

**Comment by asmusf** [comment] 2016-02-04 18:13
What Martin said.
There's also been, and continues to be some minority faction that simply writes the lowercase ß in an ALL CAPS context. 
The point of the example is to show a character that has no "simple" mapping. At the current stage, that's the ß.

**Comment by aphillips** [comment] 2016-02-07 00:51
I agree with @duerst and @asmusf. In particular, the purpose here is to point out a character whose Unicode case mapping is 'full' rather than 'simple'. Right or wrong (although I happen to think it is right), the sharp S meets that criterion.

I happen to think it is correct because, in addition to personal experience, etc., I recall the debate when U+1E9E was encoded. The main purpose cited then was, IIRC, to provide a code point for uppercase equivalent glyphs for cases like ALL CAPS TITLES in printing such as Martin mentions Duden using.

The Unicode FAQ is helpful here:

>  In standard German orthography, the sharp s ("ß") is uppercased to a sequence of two capital S 
> characters. This is a longstanding practice, and is reflected in the default case mappings in 
> Unicode. A capital form of ß is attested in a number of instances, and has thus been encoded in 
> the Unicode Standard. However, this character is not widely used, and is not recognized in the 
> official orthography as the uppercase form of ß. Therefore, the original mapping to "SS" is 
> retained in the Unicode character properties.

I'll address locale vs. language in a separate comment.

**Comment by aphillips** [comment] 2016-02-07 00:57
Regarding "locale-dependent" versus "language-dependent", the difference is that there is no difference? Or rather: locale-dependent operations are those that take a locale in order to set the language- or culturally-dependent behavior. In every programming language I can think of, case folding and case mapping take a locale (explicitly or implicitly from the environment) to control their behavior. Unicode itself has begun delegating tailorings to CLDR.

The problem is that the above is contradictory to the usage in the current draft, where I mention locale only a couple of times (and it is in relation to case folding), but not in Section 2.1. This stems from past practice in our W3C specs of speaking of "language" for content where we might otherwise say "locale". (The XML and HTML attribute is called `lang` after all). 

I will point out that [http://w3c.github.io/ltli/ LTLI] _is_ on this working group's list of Things To Do... if only we can get CharMod done ;-).

I will evaluate making language-vs.-locale terminology consistently one or the other before closing this issue.

**Comment by asmusf** [comment] 2016-02-07 01:36
On 2/6/2016 4:57 PM, aphillips wrote:

> Regarding "locale-dependent" versus "language-dependent", the 
> difference is that there is no difference? Or rather: locale-dependent 
> operations are those that take a locale in order to set the language- 
> or culturally-dependent behavior. In every programming language I can 
> think of, case folding and case mapping take a locale (explicitly or 
> implicitly from the environment) to control their behavior. Unicode 
> itself has begun delegating tailorings to CLDR.
> 
> The problem is that the above is contradictory to the usage in the 
> current draft, where I mention locale only a couple of times (and it 
> is in relation to case folding), but not in Section 2.1. This stems 
> from past practice in our W3C specs of speaking of "language" for 
> content where we might otherwise say "locale". (The XML and HTML 
> attribute is called |lang| after all).
> 
> I will point out that [http://w3c.github.io/ltli/ LTLI] /is/ on this 
> working group's list of Things To Do... if only we can get CharMod 
> done ;-).
> 
> I will evaluate making language-vs.-locale terminology consistently 
> one or the other before closing this issue.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/w3c/charmod-norm/issues/68#issuecomment-180904273.

The waters get muddied by the habit of using territorial information to 
designate varieties of language use, and then treating those constructs 
again as "language".

Casing operations should, in principle be tied to an orthography. The 
latter, if standardized, is usually standardized for a given territory 
(or group of territories).

But once you roll all combinations of territory and language into a 
single construct each, there's no longer a way to cleanly single out 
"language" or anything from it.

**Comment by aphillips** [comment] 2016-02-20 09:00
I reviewed the use of the terms locale and language in the draft. Language is used almost universally. Of the three references to locale, one was in the name of CLDR. Another was used with the term language in describing case folding. The last was used in a requirement. I replaced the one case in the requirement. See above commit for the deltas.

@klensin Please reopen this issue if not satisfied.

**Closed as completed by aphillips** 2016-02-20 09:00 UTC
